excluded:
 - Pods
 - ZeroWasteFriendly/Support/R.generated.swift
 - Templates

line_length:
 warning: 160
 error: 180

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 50

function_parameter_count:
  warning: 5
  error: 5

opt_in_rules:
- empty_count
- empty_string
- fatal_error_message
- first_where
- for_where
- force_unwrapping
- force_cast
- multiline_function_chains
- multiline_parameters
- private_outlet
- private_action
- private_over_fileprivate
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- sorted_first_last
- strict_fileprivate
- switch_case_on_newline
- todo
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- yoda_condition

disabled_rules:
 - identifier_name
 - type_name
 - trailing_whitespace
 - nesting
 - force_try
 - block_based_kvo
 - notification_center_detachment
 - cyclomatic_complexity
